// Format an agent run into a shareable report — Markdown (for humans / PRs / tickets) or JSON (for
// tooling). Pure, no engine deps. The two tiers stay clearly separated: PROVEN (zero-FP, confirmed by a
// benign proof) vs POTENTIAL (unproven leads for manual review) — the report never blurs them.

const SEV = { critical: 0, high: 1, medium: 2, low: 3, info: 4 };
const sevSort = (a, b) => (SEV[a.severity] ?? 9) - (SEV[b.severity] ?? 9);

export function toMarkdown(run = {}, meta = {}) {
  const findings = (run.findings || []).slice().sort(sevSort);
  const leads = run.leads || [];
  const s = run.stats || {};
  const out = [];
  out.push('# Securovix Shannon — Agent Report');
  out.push('');
  if (meta.target) out.push(`**Target:** ${meta.target}  `);
  if (meta.date) out.push(`**Date:** ${meta.date}  `);
  out.push(
    `**Summary:** ${s.confirmed ?? findings.length} proven · ${leads.length} potential · ${s.rounds || 1} round(s) · ${s.tested || 0} probes`,
  );
  out.push('');
  out.push(
    '> **Proven** findings are confirmed by a benign proof — zero false positives. **Potential** items are UNPROVEN leads surfaced for manual review; they are kept strictly separate and must not be treated as confirmed.',
  );

  out.push('');
  out.push(`## Proven findings (${findings.length})`);
  if (!findings.length) {
    out.push('');
    out.push('_None — every probe abstained. No proof, no finding._');
  }
  for (const f of findings) {
    out.push('');
    out.push(
      `### ${f.cls || f.tool || 'finding'} — ${String(f.severity || '').toUpperCase()}${f.impact ? ' (impact)' : ''}`,
    );
    if (f.target) out.push(`- **Where:** ${f.target}`);
    if (f.detail) out.push(`- **Evidence:** ${String(f.detail).replace(/\n+/g, ' ')}`);
    if (f.fix) out.push(`- **Fix:** ${f.fix}`);
  }

  if (leads.length) {
    out.push('');
    out.push(`## Potential — needs review (${leads.length}, UNPROVEN)`);
    for (const l of leads) {
      out.push('');
      out.push(`- **${l.kind || 'lead'}** — ${l.note || ''}`);
      if (l.target) out.push(`  \`${l.target}\``);
    }
  }

  out.push('');
  out.push('---');
  out.push('_Generated by Securovix Shannon · Proven = confirmed by proof · Potential = unverified lead._');
  return out.join('\n');
}

export function toJson(run = {}, meta = {}) {
  return JSON.stringify(
    {
      tool: 'securovix-shannon',
      target: meta.target || null,
      date: meta.date || null,
      stats: run.stats || {},
      findings: run.findings || [],
      leads: run.leads || [],
    },
    null,
    2,
  );
}

// SARIF 2.1.0 — consumable by GitHub code scanning / CI. Only the PROVEN (confirmed) findings become
// results (SARIF is for real findings); the potential tier is intentionally excluded.
const SARIF_LEVEL = { critical: 'error', high: 'error', medium: 'warning', low: 'note', info: 'note' };
const SEV_SCORE = { critical: 9.5, high: 8, medium: 5, low: 3, info: 1 };
export function toSarif(run = {}, meta = {}) {
  const rules = new Map();
  const results = (run.findings || []).map((f) => {
    const id = String(f.cls || f.tool || 'finding');
    if (!rules.has(id))
      rules.set(id, {
        id,
        name: id,
        shortDescription: { text: id },
        help: { text: f.fix || 'See the Shannon agent report for remediation.' },
        properties: { 'security-severity': String(SEV_SCORE[f.severity] ?? 0), tags: ['security'] },
      });
    let uri = f.target || meta.target || '';
    try {
      new URL(uri);
    } catch {
      uri = meta.target || uri;
    }
    return {
      ruleId: id,
      level: SARIF_LEVEL[f.severity] || 'warning',
      message: { text: String(f.detail || id).slice(0, 400) },
      locations: [{ physicalLocation: { artifactLocation: { uri } } }],
      properties: { severity: f.severity, impact: !!f.impact, fix: f.fix || null },
    };
  });
  return {
    $schema: 'https://json.schemastore.org/sarif-2.1.0.json',
    version: '2.1.0',
    runs: [
      {
        tool: {
          driver: {
            name: 'Securovix Shannon (Agent)',
            version: '1.0.0',
            informationUri: 'https://securovix.com',
            rules: [...rules.values()],
          },
        },
        results,
        properties: { target: meta.target || null, scannedAt: meta.date || null },
      },
    ],
  };
}
