// Format an agent run into a shareable report — Markdown (for humans / PRs / tickets) or JSON (for
// tooling). Pure, no engine deps. The two tiers stay clearly separated: PROVEN (zero-FP, confirmed by a
// benign proof) vs POTENTIAL (unproven leads for manual review) — the report never blurs them.

const SEV = { critical: 0, high: 1, medium: 2, low: 3, info: 4 };
const sevSort = (a, b) => (SEV[a.severity] ?? 9) - (SEV[b.severity] ?? 9);

export function toMarkdown(run = {}, meta = {}) {
  const findings = (run.findings || []).slice().sort(sevSort);
  const leads = run.leads || [];
  const s = run.stats || {};
  const out = [];
  out.push('# Securovix Shannon — Agent Report');
  out.push('');
  if (meta.target) out.push(`**Target:** ${meta.target}  `);
  if (meta.date) out.push(`**Date:** ${meta.date}  `);
  out.push(
    `**Summary:** ${s.confirmed ?? findings.length} proven · ${leads.length} potential · ${s.rounds || 1} round(s) · ${s.tested || 0} probes`,
  );
  out.push('');
  out.push(
    '> **Proven** findings are confirmed by a benign proof — zero false positives. **Potential** items are UNPROVEN leads surfaced for manual review; they are kept strictly separate and must not be treated as confirmed.',
  );

  out.push('');
  out.push(`## Proven findings (${findings.length})`);
  if (!findings.length) {
    out.push('');
    out.push('_None — every probe abstained. No proof, no finding._');
  }
  for (const f of findings) {
    out.push('');
    out.push(
      `### ${f.cls || f.tool || 'finding'} — ${String(f.severity || '').toUpperCase()}${f.impact ? ' (impact)' : ''}`,
    );
    if (f.target) out.push(`- **Where:** ${f.target}`);
    if (f.detail) out.push(`- **Evidence:** ${String(f.detail).replace(/\n+/g, ' ')}`);
    if (f.fix) out.push(`- **Fix:** ${f.fix}`);
  }

  if (leads.length) {
    out.push('');
    out.push(`## Potential — needs review (${leads.length}, UNPROVEN)`);
    for (const l of leads) {
      out.push('');
      out.push(`- **${l.kind || 'lead'}** — ${l.note || ''}`);
      if (l.target) out.push(`  \`${l.target}\``);
    }
  }

  out.push('');
  out.push('---');
  out.push('_Generated by Securovix Shannon · Proven = confirmed by proof · Potential = unverified lead._');
  return out.join('\n');
}

export function toJson(run = {}, meta = {}) {
  return JSON.stringify(
    {
      tool: 'securovix-shannon',
      target: meta.target || null,
      date: meta.date || null,
      stats: run.stats || {},
      findings: run.findings || [],
      leads: run.leads || [],
    },
    null,
    2,
  );
}
